open Bio_util
open Bio_geom

let parse_xyz_line line =
  match String.split_on_char ' ' line |> List.filter ((<>) "") with
  | x :: y :: z :: _ ->
      begin match float_opt x, float_opt y, float_opt z with
      | Some x, Some y, Some z -> Some (of_xyz x y z)
      | _ -> None
      end
  | _ -> None

let read_xyz_frames filename =
  In_channel.with_open_text filename @@ fun ic ->
  let rec read_frame acc =
    match In_channel.input_line ic with
    | None -> List.rev acc
    | Some line ->
        let n =
          match int_opt line with
          | Some n -> n
          | None -> 0
        in
        if n = 0 then
          List.rev acc
        else
          let first_line = In_channel.input_line ic in
          let first_coord =
            match first_line with
            | None -> None
            | Some l -> parse_xyz_line l
          in
          let rec read_atoms coords count =
            if count = n then
              List.rev coords
            else
              match In_channel.input_line ic with
              | None -> List.rev coords
              | Some l ->
                  begin match parse_xyz_line l with
                  | None -> read_atoms coords count
                  | Some c -> read_atoms (c :: coords) (count + 1)
                  end
          in
          let frame =
            match first_coord with
            | None -> read_atoms [] 0
            | Some c -> read_atoms [c] 1
          in
          read_frame (frame :: acc)
  in
  read_frame []

let read_xyz filename =
  match read_xyz_frames filename with
  | first :: _ -> first
  | [] -> []

let write_xyz ?(comment="generated by bio_xyz") filename coords =
  Out_channel.with_open_text filename @@ fun oc ->
  Out_channel.output_string oc (Printf.sprintf "%d\n" (List.length coords));
  Out_channel.output_string oc (comment ^ "\n");
  List.iter (fun c ->
    Out_channel.output_string oc (Printf.sprintf "%f %f %f\n" c.x c.y c.z)
  ) coords

let write_xyz_frames ?(comment="generated by bio_xyz") filename frames =
  Out_channel.with_open_text filename @@ fun oc ->
  List.iter (fun frame ->
    Out_channel.output_string oc (Printf.sprintf "%d\n" (List.length frame));
    Out_channel.output_string oc (comment ^ "\n");
    List.iter (fun c ->
      Out_channel.output_string oc (Printf.sprintf "%f %f %f\n" c.x c.y c.z)
    ) frame
  ) frames
