open Bio_util

type atom = {
  serial : int;
  resid : int;
  resname : string;
  atomname : string;
  x : float;
  y : float;
  z : float;
  segid : string option;
  resid2 : int option;
  weight : float option;
}

type crd = {
  title : string list;
  atoms : atom list;
}

let is_title_line line =
  let t = trim line in
  t <> "" && t.[0] = '*'

let parse_atom_fields fields =
  match fields with
  | serial :: resid :: resname :: atomname :: x :: y :: z :: rest ->
      let segid = match rest with | s :: _ -> string_opt s | [] -> None in
      let resid2 = match rest with | _ :: s :: _ -> int_opt s | _ -> None in
      let weight = match rest with | _ :: _ :: s :: _ -> float_opt s | _ -> None in
      begin
        match int_opt serial, int_opt resid, float_opt x, float_opt y, float_opt z with
        | Some serial, Some resid, Some x, Some y, Some z ->
            Some {
              serial; resid; resname; atomname; x; y; z; segid; resid2; weight;
            }
        | _ -> None
      end
  | _ -> None

let read_crd filename =
  In_channel.with_open_text filename @@ fun ic ->
  let rec read_title acc =
    match In_channel.input_line ic with
    | None -> List.rev acc, None
    | Some line ->
        if is_title_line line then
          read_title (line :: acc)
        else
          List.rev acc, Some line
  in
  let title, first = read_title [] in
  let rec skip_blank = function
    | None -> None
    | Some line ->
        if trim line = "" then
          (match In_channel.input_line ic with
           | None -> None
           | Some next -> skip_blank (Some next))
        else
          Some line
  in
  let header = skip_blank first in
  let natoms =
    match header with
    | None -> 0
    | Some line ->
        match int_opt line with
        | Some n -> n
        | None ->
            (* Some CRD headers have extra tokens, take first int. *)
            let fields = String.split_on_char ' ' line |> List.filter ((<>) "") in
            match fields with
            | n :: _ -> int_of_string n
            | [] -> 0
  in
  let rec read_atoms acc count =
    if count = natoms then
      List.rev acc
    else
      match In_channel.input_line ic with
      | None -> List.rev acc
      | Some line ->
          let fields = String.split_on_char ' ' line |> List.filter ((<>) "") in
          begin match parse_atom_fields fields with
          | None -> read_atoms acc count
          | Some atom -> read_atoms (atom :: acc) (count + 1)
          end
  in
  { title; atoms = read_atoms [] 0 }

let write_crd ?(title=["* Generated by bio_crd.ml"]) filename atoms =
  Out_channel.with_open_text filename @@ fun oc ->
  List.iter (fun line -> Out_channel.output_string oc (line ^ "\n")) title;
  Out_channel.output_string oc (Printf.sprintf "%8d\n" (List.length atoms));
  List.iter (fun a ->
    let segid = Option.value ~default:"" a.segid in
    let resid2 = Option.value ~default:0 a.resid2 in
    let weight = Option.value ~default:0.0 a.weight in
    Out_channel.output_string oc
      (Printf.sprintf "%10d%10d %-8s %-8s%20.10f%20.10f%20.10f %-8s%-8d%20.10f\n"
         a.serial a.resid a.resname a.atomname a.x a.y a.z segid resid2 weight)
  ) atoms
