open Bio_util

type record =
  | Atom
  | Hetatm

type atom = {
  record : record;
  serial : int;
  name : string;
  alt_loc : char option;
  res_name : string;
  chain_id : char option;
  res_seq : int;
  i_code : char option;
  x : float;
  y : float;
  z : float;
  occupancy : float option;
  temp_factor : float option;
  seg_id : string option;
  element : string option;
  charge : string option;
}

let record_of_string = function
  | "ATOM  " -> Some Atom
  | "HETATM" -> Some Hetatm
  | _ -> None

let parse_atom_line line =
  (* Fixed-width PDB columns, 1-based in spec.
     1-6 record, 7-11 serial, 13-16 name, 17 altLoc, 18-20 resName,
     22 chainID, 23-26 resSeq, 27 iCode, 31-38 x, 39-46 y, 47-54 z,
     55-60 occupancy, 61-66 tempFactor, 73-76 segID, 77-78 element, 79-80 charge. *)
  let record = safe_sub line 0 6 in
  match record_of_string record with
  | None -> None
  | Some record ->
      let serial = int_opt (safe_sub line 6 5) in
      let name = trim (safe_sub line 12 4) in
      let alt_loc = char_opt line 16 in
      let res_name = trim (safe_sub line 17 3) in
      let chain_id = char_opt line 21 in
      let res_seq = int_opt (safe_sub line 22 4) in
      let i_code = char_opt line 26 in
      let x = float_opt (safe_sub line 30 8) in
      let y = float_opt (safe_sub line 38 8) in
      let z = float_opt (safe_sub line 46 8) in
      let occupancy = float_opt (safe_sub line 54 6) in
      let temp_factor = float_opt (safe_sub line 60 6) in
      let seg_id = string_opt (safe_sub line 72 4) in
      let element = string_opt (safe_sub line 76 2) in
      let charge = string_opt (safe_sub line 78 2) in
      begin
        match serial, res_seq, x, y, z with
        | Some serial, Some res_seq, Some x, Some y, Some z ->
            Some {
              record; serial; name; alt_loc; res_name; chain_id; res_seq; i_code;
              x; y; z; occupancy; temp_factor; seg_id; element; charge;
            }
        | _ -> None
      end

let read_pdb_atoms filename =
  In_channel.with_open_text filename @@ fun ic ->
  let rec loop acc =
    match In_channel.input_line ic with
    | None -> List.rev acc
    | Some line ->
        match parse_atom_line line with
        | None -> loop acc
        | Some atom -> loop (atom :: acc)
  in
  loop []

let atoms_to_xyz atoms =
  let b = Buffer.create 256 in
  Buffer.add_string b (string_of_int (List.length atoms));
  Buffer.add_char b '\n';
  Buffer.add_string b "generated by bio_pdb\n";
  List.iter (fun a ->
    Buffer.add_string b
      (Printf.sprintf "%f %f %f\n" a.x a.y a.z)
  ) atoms;
  Buffer.contents b

let format_atom_line a =
  let record =
    match a.record with
    | Atom -> "ATOM"
    | Hetatm -> "HETATM"
  in
  let alt = match a.alt_loc with None -> ' ' | Some c -> c in
  let chain = match a.chain_id with None -> ' ' | Some c -> c in
  let icode = match a.i_code with None -> ' ' | Some c -> c in
  let occ = match a.occupancy with None -> 0.00 | Some v -> v in
  let temp = match a.temp_factor with None -> 0.00 | Some v -> v in
  let seg = match a.seg_id with None -> "" | Some s -> s in
  let elem = match a.element with None -> "" | Some s -> s in
  let charge = match a.charge with None -> "" | Some s -> s in
  Printf.sprintf "%-6s%5d %-4s%c%-3s %c%4d%c   %8.3f%8.3f%8.3f%6.2f%6.2f      %-4s%2s%2s"
    record a.serial a.name alt a.res_name chain a.res_seq icode
    a.x a.y a.z occ temp seg elem charge

let write_pdb filename atoms =
  Out_channel.with_open_text filename @@ fun oc ->
    List.iter (fun a ->
      Out_channel.output_string oc (format_atom_line a);
      Out_channel.output_char oc '\n'
    ) atoms
